// ui/src/typescript/components/Landing.vue
<template>
  <div id="landing">
    <div class="row">
      <div class="col-sm-4 offset-sm-4">
        <form @submit.prevent="goVote">
          <div class="form-group">
            <label for="this.user.name"></label>
            <input type="text"
                   maxlength="60"
                   v-model="user.name"
                   class="form-control"
                   id="this.user.name"
                   placeholder="Your name/alias">
            <div class="invalid-feedback">
            </div>
          </div>
          <button type="button" class="btn btn-lg btn-warning" v-on:click="goVote">New Voting Space</button>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import {User} from "../models";
  import HttpMixin from "./HttpMixin";
  import { Component, Mixins } from 'vue-mixin-decorator';

  @Component
  export default class Landing extends Mixins<HttpMixin>(HttpMixin)  {
    user = new User();
    sessionId: string = "";

    beforeCreate() {
      document.body.className = 'bg';
    }

    goVote() {
      this.postRequest("/api/session", {}).then((resp) => {
        return resp.json();
      }).then((json) => {
        this.sessionId = json['id'];
        return Promise.resolve(this.sessionId);
      }).then(() => {
        return this.postRequest("/api/user", {
          'name': this.user.name,
          'session_id': this.sessionId
        });
      }).then((resp) => {
        return resp.json()
      }).then((json) => {
        this.user.id = json['id'];
        this.putRequest("/api/vote/start", {
          'session_id': this.sessionId
        });
      }).then(() => {
        this.$router.push({name: 'ballot', params: {
            sessionId: this.sessionId,
            userId: this.user.id
          }});
      }).catch((err: Error) => {
        this.showError(err);
      });
    }
  }
</script>

// ballot-ui/src/views/landing.tsx
import './landing.css'
import React from 'react'
import Brand from '../components/brand.tsx'
import Footer from '../components/footer.tsx'
import axios from 'axios'

function Landing(): React.JSX.Element {
    let sessionId: string | null = null

    async function createNewSession(): Promise<void> {
        axios
            .post('/api/session')
            .then((response) => {
                sessionId = response.data.id
            })
            .then(() => {
                console.log(sessionId)
            })
            .catch((error) => console.error(error))
    }

    return (
        <div id="Landing">
            <Brand />

            <div className="form">
                <form>
                    <label htmlFor=""></label>
                    <input
                        type="text"
                        maxLength={64}
                        placeholder="Your name/alias"
                    />
                    <button type="button" onClick={createNewSession}>
                        New Voting Space
                    </button>
                </form>
            </div>

            <Footer />
        </div>
    )
}

export default Landing
